### ISSUE TITLE
Add login/password system (???)

### ISSUE THREAD

**Issue by andeason** [andeason/Project#10]
So, I made a basic idea of a login password with username or password.  I believe this wasnt listed in the schema, so if there are any complaints, do list them.  Regardless, we do need a system to verify that a user can only be at one section.

If there are no complaints, some additional functionalities can be added to make more complex:

Firstly, a password reset can be done, where the employee can give say their ID, first name, and last name to change.  Then, they can give a new password and/or username to the system.

**Comment by MichaelGumm** [comment]
I'll start working on this
