### ISSUE TITLE
Add functionalities from Manager to Stocker

### ISSUE THREAD

**Issue by andeason** [andeason/Project#3]
Functionalities that should be shared with the Stocker (ex: Receipts, etc).  Have not been linked yet.  Someone should add buttons and calls to the stocker main page to redirect to these sections. 

Ones needed to be added are:
Employee List
Show Orders
Show Receipts

Additionally, check to ensure that they can actually view them when login and that they arent restricted to only a manager.

**Comment by andeason** [comment]
This should be done.

**Comment by MichaelGumm** [comment]
As far as I know Stockers cannot view orders or reciepts yet.
